
dist: precise

language: php
php:
  - 5.3

cache:
  apt: true

addons:
  apt:
    sources:
    packages:
      - apache2
      - mysql-server-5.5
      - libapache2-mod-php5
      - php5-curl
      - php5-gd
      - php5-mysql

before_script:
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

script: echo 'Test'
