sudo: false

dist: precise

language: php
php:
  - 5.3

cache:
  apt: true

addons:
  apt:
    sources:
    packages:
      - apache2
      - mysql-server-5.5
      - libapache2-mod-php5
      - php5-curl
      - php5-gd
      - php5-mysql

before_script:
  - mkdir test

script: echo 'Test'
